### ISSUE TITLE
Enhancing Web Accessibility and User Experience Through Dynamic Contributor Display

### ISSUE THREAD

**Issue by srijan2607** [M-Hidayatullah/hacktoberfest-2024#1]
1.	Code Modularity: The need for reusable code components to simplify the addition of new contributors in the future.
	2.	Readability: The initial code structure lacked clarity, making it challenging for developers to understand and modify.
	3.	Accessibility: Ensuring that images are appropriately tagged with alt text to improve accessibility for visually impaired users.

**Comment by srijan2607** [comment]
@M-Hidayatullah please assign this to me

**Comment by M-Hidayatullah** [comment]
> @M-Hidayatullah please assign this to me

oke
